### ISSUE TITLE
Need help! About generate human image with ipa and depth conrtolnet. 

### ISSUE THREAD

**Issue by silence-tang** [yisuanwang/Ultraman#4]
Hi, this is a great work! It inspired me a lot.
I have a question. When I use side view depth map rendered from a smplx model to guide ipadapter, the generated human always looks at the "outside" of the screen, could you please give me some advice? Thanks a lot!
![depth](https://github.com/yisuanwang/Ultraman/assets/56212320/dcf4701b-69d5-4669-98ce-b16e28a26ee8)
![face](https://github.com/yisuanwang/Ultraman/assets/56212320/7765dc94-b758-417d-9727-e27aa8b4e928)
![output](https://github.com/yisuanwang/Ultraman/assets/56212320/a97dddc5-7e48-4a9c-b3df-6878a80471e3)

**Comment by yisuanwang** [comment]
似乎由于你ipadapter用的是单张人脸图片？我们之前一直是使用一张完整的人体照片作为image prompt的

**Comment by silence-tang** [comment]
> 似乎由于你ipadapter用的是单张人脸图片？我们之前一直是使用一张完整的人体照片作为image prompt的

谢谢您的回复！好像确实是因为我的image prompt用的单张正面人脸，模型为了符合这个prompt所以生成的所有视角脸都是趋向于正面的。
我还有一些问题请教您：
1. 生成多视角图像时用的depth map和生成的image用的分辨率分别是多少，512x512 / 512x768或更高？
2. 当输入的depth是不同视角时，理论上ipa+controlnet不能保证生成的不同视角图像的衣着纹理和面部特征是一致的，但论文中展示的结果一致性还挺高的，这个你们是如何处理的。
谢谢。

**Comment by yisuanwang** [comment]
depth和image prompt都是1024的，相比于512的图片，1024能显著提升质量
---- Replied Message ----
***@***.***>Date07/05/2024 17:34 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [yisuanwang/Ultraman] Need help! About generate human image with ipa and depth conrtolnet. (Issue #4)
似乎由于你ipadapter用的是单张人脸图片？我们之前一直是使用一张完整的人体照片作为image prompt的
谢谢您的回复！好像确实是因为我的image prompt用的单张正面人脸，模型为了符合这个prompt所以生成的所有视角脸都是趋向于正面的。
我还有一些问题请教您：
生成多视角图像时用的depth map和生成的image用的分辨率分别是多少，512x512 / 512x768或更高？
当输入的depth是不同视角时，理论上ipa+controlnet不能保证生成的不同视角图像的衣着纹理和面部特征是一致的，但论文中展示的结果一致性还挺高的，这个你们是如何处理的。
谢谢。

**Comment by silence-tang** [comment]
> depth和image prompt都是1024的，相比于512的图片，1024能显著提升质量 ---- Replied Message ---- ***@***.***>Date07/05/2024 17:34 ***@***.***> ***@***.***>, ***@***.***>SubjectRe: [yisuanwang/Ultraman] Need help! About generate human image with ipa and depth conrtolnet. (Issue #4) 似乎由于你ipadapter用的是单张人脸图片？我们之前一直是使用一张完整的人体照片作为image prompt的 谢谢您的回复！好像确实是因为我的image prompt用的单张正面人脸，模型为了符合这个prompt所以生成的所有视角脸都是趋向于正面的。 我还有一些问题请教您： 生成多视角图像时用的depth map和生成的image用的分辨率分别是多少，512x512 / 512x768或更高？ 当输入的depth是不同视角时，理论上ipa+controlnet不能保证生成的不同视角图像的衣着纹理和面部特征是一致的，但论文中展示的结果一致性还挺高的，这个你们是如何处理的。 谢谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的，谢谢。

**Comment by silence-tang** [comment]
还有一个问题是如果image prompt是全身人像的话，如何让生成的正面人像的面部特征看起来更贴近输入的人呢，这个是只能通过更全面的VQA结果保证，还是有其他途径？
我给了个大概的text prompt（不如论文中的VQA结果描述的全面）然后测试了一下论文中的男人图，感觉生成的保id效果还不太行。
![man](https://github.com/yisuanwang/Ultraman/assets/56212320/4fe96ab4-0bd2-4517-9758-b02d58f2e9da)
![output](https://github.com/yisuanwang/Ultraman/assets/56212320/6b78695b-ec8e-41ca-9f23-395ba35d215b)

**Comment by yisuanwang** [comment]
在纹理映射步骤中，正面区域使用的是输入图像而非生成图像

**Comment by silence-tang** [comment]
> 在纹理映射步骤中，正面区域使用的是输入图像而非生成图像

嗯嗯这个我知道的。我是想知道如果单纯想用ipadapter+depth controlnet生成正面人体全身图像，怎么才能让生成图像的面部id更贴近输入？因为我看你们的paper中ipadapter生成的结果面部id保持的很好，比我上面生成的那两张图好很多。
<img width="428" alt="cmp" src="https://github.com/yisuanwang/Ultraman/assets/56212320/14837bde-c0b9-4037-ae1e-e9bd0edd5f89">

此外你们用的是sdxl作为base unet，sdxl相比sd1.5而言，对效果提升明显吗？

再次感谢您的耐心解答！

**Comment by yisuanwang** [comment]
sdxl相比sd1.5而言在1024分辨率下生成的人的纹理质量要高很多。我不是很理解你说的“paper中ipadapter生成的结果面部id保持的很好”，因为我们生成的人体模型所使用的正面纹理与输入图像完全相同（paper中的图可能存在一些误解，实际上我们没有使用生成的正面纹理进行映射，而是使用输入的原图）。

**Comment by silence-tang** [comment]
对，我知道你们没使用生成的正面纹理进行映射，只是说你们用ipadapter生成的正面人像的脸和image prompt很相似（如下图所示，你们用渲染出来的正面depth+image prompt生成了右边那个正面图，而这个正面图的脸看起来和image prompt很相似，是我想达到的效果），但是我上面生成的结果的脸和image prompt不相似，不知道是什么原因。ps: 我用的ipadapter+sd1.5，没用ipadapter_faceid_plus。

<img width="877" alt="1" src="https://github.com/yisuanwang/Ultraman/assets/56212320/8d5ff152-4c29-4316-a2e0-7a39519a1633">

**Comment by yisuanwang** [comment]
你可以先试试sdxl+ ipadapter_faceid_plus，我们之前试过了sd1.5和ipadapter的非faceid模型，不是很work才换到sdxl的

**Comment by silence-tang** [comment]
多谢，我也猜测是这个原因。我去试试。

**Comment by silence-tang** [comment]
我试了一下ipadapter_faceid_plus_v2 （因为官方只提供了v2的sdxl预训练模型） + sdxl，下面是我的配置：
- base_model_path = "/data/tangzichen/SG161222/RealVisXL_V3.0"
- image_encoder_path = "/data/tangzichen/laion/CLIP-ViT-H-14-laion2B-s32B-b79K"
- ip_ckpt = "/data/tangzichen/IP-Adapter/models/ip-adapter-faceid-plusv2_sdxl.bin" # a experimental version
- controlnet_depth_path = '/data/tangzichen/diffusers/controlnet-depth-sdxl-1.0'
生成图像的语句是：
prompt = "A man in a navy blue T-shirt, blue jeans, and brown boots, with short dark hair and a beard, wearing a wristwatch and bracelet, pure white background"
negative_prompt = ""
v2 = True
images = ip_model.generate(
     prompt=prompt,
     negative_prompt=negative_prompt,
     face_image=face_image,
     faceid_embeds=faceid_embeds,
     image=depth_image,
     shortcut=v2,
     scale=1,  # default
     s_scale=1, #  default
     num_samples=1,
     width=1024,
     height=1024,
     num_inference_steps=30,
     guidance_scale=7.5,
     seed=2023
)
用的image prompt是：
<img width="364" alt="man" src="https://github.com/yisuanwang/Ultraman/assets/56212320/d919e29c-518b-40bf-9ea0-aef739653ed8">

用的深度图是：
<img width="364" alt="depth_man_side" src="https://github.com/yisuanwang/Ultraman/assets/56212320/3b4067d7-05b7-49d0-a9cb-9b75b0ced424">

结果是：
![output](https://github.com/yisuanwang/Ultraman/assets/56212320/0a6e64cd-779f-469f-94d5-661a0f8b7bba)

你们的结果是：
<img width="494" alt="图片 1" src="https://github.com/yisuanwang/Ultraman/assets/56212320/1a026cda-39c7-4ca2-83dc-4c0500049579">

看起来人物的侧脸还是有我一开始提的那个问题，就是不能完全侧过去，总是对着屏幕外看。不知道能否参考一下你们生成图像时用的配置？此外，你之前指出我生成的图像脸总是朝外看可能是因为我用的是单张人脸，而你用的是全身人像。但ipadapter_faceid_plus输入模型的是crop出来的人脸，而非全身人像：`face_image = face_align.norm_crop(image, landmark=faces[0].kps, image_size=224)`，所以我还是不太清楚为啥你生成的侧面人像的脸可以真的侧过去，希望大佬给个解答，你们的经验很宝贵。这问题困扰我一阵子了www。

**Comment by yisuanwang** [comment]
1. prompt里似乎需要添加方向提示，the view of xxx
2. 你给出的结果，是我们生成完每一个视角的texture，映射回mesh后的侧面视角渲染结果，所以侧面更新的texture mask中不包含正面视角（即你可以简单理解为，缝隙的左侧是侧面这张图的纹理，缝隙的右侧是正面texture映射回mesh的）。
3. 我们无法保证你在右侧生成的texture的脸部一定是朝右的，这取决于你depth的质量（分辨率）和参考图像的质量（分辨率）
4. 我们一开始用的貌似是这个：    
    - base_model_path = "stabilityai/stable-diffusion-xl-base-1.0"
    - image_encoder_path = "models/IP_Adapter/models/image_encoder"
    - ip_ckpt = "models/IP_Adapter/sdxl_models/ip-adapter_sdxl_vit-h.bin"

希望对你有帮助！

**Comment by silence-tang** [comment]
> 1. prompt里似乎需要添加方向提示，the view of xxx
> 2. 你给出的结果，是我们生成完每一个视角的texture，映射回mesh后的侧面视角渲染结果，所以侧面更新的texture mask中不包含正面视角（即你可以简单理解为，缝隙的左侧是侧面这张图的纹理，缝隙的右侧是正面texture映射回mesh的）。
> 3. 我们无法保证你在右侧生成的texture的脸部一定是朝右的，这取决于你depth的质量（分辨率）和参考图像的质量（分辨率）
> 4. 我们一开始用的貌似是这个：
>    
>    * base_model_path = "stabilityai/stable-diffusion-xl-base-1.0"
>    * image_encoder_path = "models/IP_Adapter/models/image_encoder"
>    * ip_ckpt = "models/IP_Adapter/sdxl_models/ip-adapter_sdxl_vit-h.bin"
> 
> 希望对你有帮助！

好的，谢谢你！
